-- AlterEnum
BEGIN;
CREATE TYPE "AuditEventType_new" AS ENUM ('LOGIN_SUCCESS', 'LOGOUT', 'BRUTE_FORCE_DETECTED', 'RATE_LIMIT_VIOLATION', 'WORKSPACE_CREATED', 'WORKSPACE_UPDATED', 'WORKSPACE_ARCHIVED', 'WORKSPACE_DELETED', 'WORKSPACE_SETTINGS_CHANGED', 'WORKSPACE_MEMBER_INVITED', 'WORKSPACE_MEMBER_REMOVED', 'WORKSPACE_MEMBER_ROLE_CHANGED', 'PROJECT_CREATED', 'PROJECT_ARCHIVED', 'PROJECT_DELETED', 'PROJECT_MEMBER_ADDED', 'PROJECT_MEMBER_REMOVED', 'TASK_CREATED', 'TASK_DELETED', 'TASK_STATUS_CHANGED', 'TASK_ASSIGNEE_CHANGED', 'TASK_DESCRIPTION_CHANGED', 'TASK_DUE_DATE_CHANGED', 'SUBTASK_CREATED', 'SUBTASK_ASSIGNED', 'COMMENT_ADDED', 'COMMENT_DELETED_BY_ADMIN', 'ATTACHMENT_UPLOADED', 'ATTACHMENT_DELETED', 'MEETING_REQUESTED', 'PROJECT_SETTINGS_CHANGED', 'PROJECT_MEMBER_ROLE_CHANGED');

ALTER TABLE "AuditLog" ALTER COLUMN "event" TYPE text;

UPDATE "AuditLog" SET "event" = 'WORKSPACE_MEMBER_INVITED' WHERE "event" = 'MEMBER_INVITED';
UPDATE "AuditLog" SET "event" = 'WORKSPACE_MEMBER_REMOVED' WHERE "event" = 'MEMBER_REMOVED';
UPDATE "AuditLog" SET "event" = 'WORKSPACE_MEMBER_ROLE_CHANGED' WHERE "event" = 'MEMBER_ROLE_CHANGED';
UPDATE "AuditLog" SET "event" = 'PROJECT_SETTINGS_CHANGED' WHERE "event" = 'PROJECT_UPDATED';

ALTER TABLE "AuditLog" ALTER COLUMN "event" TYPE "AuditEventType_new" USING ("event"::text::"AuditEventType_new");
ALTER TYPE "AuditEventType" RENAME TO "AuditEventType_old";
ALTER TYPE "AuditEventType_new" RENAME TO "AuditEventType";
DROP TYPE "public"."AuditEventType_old";
COMMIT;

